Magic Blog milestone 13 : Authorization
kosher9/Magic_Blog pull request #13
Opened 2022-07-21 18:49 UTC by Nemwel-Boniface

## Hello reviewer(s)

This is @kosher9 and @Nemwel-Boniface :sunglasses: 

In this milestone we were able to:

- [ ] Install CanCanCan in your project
- [ ] Add a role column to the user's table
- [ ] Implement A user can delete a post if it is theirs or if they have an admin role
- [ ] Implement A user can delete a comment if it is theirs or if they have an admin role

In case you face any challenge creating the db run the following:

`rake db:drop`
`rake db:create`
`rake db:schema:load`
`rake db:migrate` 

Thank you for taking the time to review my project :pray:

2022-07-21 22:58 UTC, RolandM99 requested changes
Hi @kosher9, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Github flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Rolandm99 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-21 22:58 UTC, RolandM99 commented on app/models/ability.rb
> +    can :destroy, [Post, Comment]
- [ ] You didn't yet implement your authorization as expected. for now, even the user who is not the owner of a post had the authorization to delete a comment. Kindly, fix this issue. You can take a look at this code below to know how to implement it.
```ruby
 class Ability
 include CanCan::Ability

     def initialize(user)

           user ||= User.new # guest user (not logged in)
  
           if user.admin? 
           can :manage, :all
         else
           can :manage, Post, author: user
           can :manage, Comment, author: user
           can :read, :all
         end
     end
 end
```
Kindly, try to fix that issue.

2022-07-22 01:23 UTC, Rustamxon7 requested changes
Hi @Nemwel-Boniface, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
_Your project is almost complete!_
_No Linters errors_


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-22 01:23 UTC, Rustamxon7 commented on app/controllers/posts_controller.rb
> +  # load_and_authorize_resource
- [ ] Why did you comment load_and_authorize? To run your Ability, you need to have this.

2022-07-22 01:23 UTC, Rustamxon7 commented on app/controllers/posts_controller.rb
> +  # before_action :set_post, only: [:index, :show, :destroy]
- [ ] You do not need to have set_post if you are using load and authorize.

2022-07-22 01:23 UTC, Rustamxon7 commented on app/models/ability.rb
> +    # can :read, [Post, Comment], author: user
- [ ] Kindly remove unused commented codes.

2022-07-22 01:23 UTC, Rustamxon7 commented on app/views/posts/index.html.erb
> +<!--      <button>Button</button>-->
- [ ] Kindly remove unused commented code.

2022-07-22 03:47 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @kosher9, 

### Good job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Clean/Organized code
:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-22 04:03 UTC, merged